apiVersion: v1
kind: Secret
metadata:
  name: totem-pedidos-secret
  namespace: totem-pedidos
  labels:
    app: totem-pedidos
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_USER: dG90ZW1wZWRpZG9z  # totempedidos
  DB_PASS: dG90ZW1wZWRpZG9z  # totempedidos
  
  # MercadoPago credentials (base64 encoded)
  MP_TOKEN: QVBQX1VTUi0xOTE2Njg3ODUxNDY0Nzg0LTAzMTYyMy04MmEwZTg5OWYxNDM5YmZmOTE3MDA3MWQ0NTM5Y2Y0Zi0yMzMxNjA5MDY1  # APP_USR-1916687851464784-031623-82a0e899f1439bff9170071d4539cf4f-2331609065
  MP_USER_ID: MjMzMTYwOTA2NQ==  # 2331609065
  MP_EXTERNAL_POS_ID: RklBUE1GQVZMUE9T  # FIAPMFAVLPOS
  MP_WEBHOOK_SECRET: U0VHUkVET19XRUJIT09L  # SEGREDO_WEBHOOK
  MP_NOTIFICATION_URL: aHR0cHM6Ly95b3VyLWRvbWFpbi5jb20vcGF5bWVudHMvd2ViaG9vaw==  # https://your-domain.com/payments/webhook
